// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: kvdb/v1/kvdb.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvdbValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KvdbValue) Reset() {
	*x = KvdbValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_v1_kvdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvdbValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvdbValue) ProtoMessage() {}

func (x *KvdbValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_v1_kvdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvdbValue.ProtoReflect.Descriptor instead.
func (*KvdbValue) Descriptor() ([]byte, []int) {
	return file_kvdb_v1_kvdb_proto_rawDescGZIP(), []int{0}
}

func (x *KvdbValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvdbValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDBRequest) Reset() {
	*x = ListDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_v1_kvdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDBRequest) ProtoMessage() {}

func (x *ListDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_v1_kvdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDBRequest.ProtoReflect.Descriptor instead.
func (*ListDBRequest) Descriptor() ([]byte, []int) {
	return file_kvdb_v1_kvdb_proto_rawDescGZIP(), []int{1}
}

type ListDBReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
}

func (x *ListDBReply) Reset() {
	*x = ListDBReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_v1_kvdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDBReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDBReply) ProtoMessage() {}

func (x *ListDBReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_v1_kvdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDBReply.ProtoReflect.Descriptor instead.
func (*ListDBReply) Descriptor() ([]byte, []int) {
	return file_kvdb_v1_kvdb_proto_rawDescGZIP(), []int{2}
}

func (x *ListDBReply) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type SearchPrefixRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db        string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Table     string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	KeyPrefix string `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
}

func (x *SearchPrefixRequest) Reset() {
	*x = SearchPrefixRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_v1_kvdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPrefixRequest) ProtoMessage() {}

func (x *SearchPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_v1_kvdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPrefixRequest.ProtoReflect.Descriptor instead.
func (*SearchPrefixRequest) Descriptor() ([]byte, []int) {
	return file_kvdb_v1_kvdb_proto_rawDescGZIP(), []int{3}
}

func (x *SearchPrefixRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *SearchPrefixRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SearchPrefixRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

type SearchPrefixReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kv []*KvdbValue `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty"`
}

func (x *SearchPrefixReply) Reset() {
	*x = SearchPrefixReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_v1_kvdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPrefixReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPrefixReply) ProtoMessage() {}

func (x *SearchPrefixReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_v1_kvdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPrefixReply.ProtoReflect.Descriptor instead.
func (*SearchPrefixReply) Descriptor() ([]byte, []int) {
	return file_kvdb_v1_kvdb_proto_rawDescGZIP(), []int{4}
}

func (x *SearchPrefixReply) GetKv() []*KvdbValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db    string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Table string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_v1_kvdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_v1_kvdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_kvdb_v1_kvdb_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *SearchRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SearchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kv []*KvdbValue `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty"`
}

func (x *SearchReply) Reset() {
	*x = SearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_v1_kvdb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReply) ProtoMessage() {}

func (x *SearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_v1_kvdb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReply.ProtoReflect.Descriptor instead.
func (*SearchReply) Descriptor() ([]byte, []int) {
	return file_kvdb_v1_kvdb_proto_rawDescGZIP(), []int{6}
}

func (x *SearchReply) GetKv() []*KvdbValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

var File_kvdb_v1_kvdb_proto protoreflect.FileDescriptor

var file_kvdb_v1_kvdb_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6b, 0x76, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x76, 0x64, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x33, 0x0a, 0x09, 0x4b, 0x76, 0x64, 0x62, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x42, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x42, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x22, 0x3b, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x02, 0x6b, 0x76, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x76, 0x64, 0x62, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02, 0x6b,
	0x76, 0x22, 0x47, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x64, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x0b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x02, 0x6b, 0x76, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x76, 0x64, 0x62, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02, 0x6b,
	0x76, 0x32, 0xe8, 0x02, 0x0a, 0x04, 0x4b, 0x76, 0x64, 0x62, 0x12, 0x5d, 0x0a, 0x06, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x42, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76,
	0x31, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2d, 0x64, 0x62, 0x12, 0x8f, 0x01, 0x0a, 0x0c, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6b, 0x76, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3d, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x37, 0x12, 0x35, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x2f, 0x7b, 0x64, 0x62, 0x7d, 0x2f, 0x7b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x7d, 0x2f, 0x7b,
	0x6b, 0x65, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x7d, 0x12, 0x6f, 0x0a, 0x06, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x76, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x29, 0x12, 0x27, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x7b, 0x64, 0x62, 0x7d, 0x2f, 0x7b,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x7d, 0x2f, 0x7b, 0x6b, 0x65, 0x79, 0x7d, 0x42, 0x1a, 0x5a, 0x18,
	0x6b, 0x76, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x76,
	0x64, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kvdb_v1_kvdb_proto_rawDescOnce sync.Once
	file_kvdb_v1_kvdb_proto_rawDescData = file_kvdb_v1_kvdb_proto_rawDesc
)

func file_kvdb_v1_kvdb_proto_rawDescGZIP() []byte {
	file_kvdb_v1_kvdb_proto_rawDescOnce.Do(func() {
		file_kvdb_v1_kvdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_kvdb_v1_kvdb_proto_rawDescData)
	})
	return file_kvdb_v1_kvdb_proto_rawDescData
}

var file_kvdb_v1_kvdb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kvdb_v1_kvdb_proto_goTypes = []interface{}{
	(*KvdbValue)(nil),           // 0: api.kvdb.v1.KvdbValue
	(*ListDBRequest)(nil),       // 1: api.kvdb.v1.ListDBRequest
	(*ListDBReply)(nil),         // 2: api.kvdb.v1.ListDBReply
	(*SearchPrefixRequest)(nil), // 3: api.kvdb.v1.SearchPrefixRequest
	(*SearchPrefixReply)(nil),   // 4: api.kvdb.v1.SearchPrefixReply
	(*SearchRequest)(nil),       // 5: api.kvdb.v1.SearchRequest
	(*SearchReply)(nil),         // 6: api.kvdb.v1.SearchReply
}
var file_kvdb_v1_kvdb_proto_depIdxs = []int32{
	0, // 0: api.kvdb.v1.SearchPrefixReply.kv:type_name -> api.kvdb.v1.KvdbValue
	0, // 1: api.kvdb.v1.SearchReply.kv:type_name -> api.kvdb.v1.KvdbValue
	1, // 2: api.kvdb.v1.Kvdb.ListDB:input_type -> api.kvdb.v1.ListDBRequest
	3, // 3: api.kvdb.v1.Kvdb.SearchPrefix:input_type -> api.kvdb.v1.SearchPrefixRequest
	5, // 4: api.kvdb.v1.Kvdb.Search:input_type -> api.kvdb.v1.SearchRequest
	2, // 5: api.kvdb.v1.Kvdb.ListDB:output_type -> api.kvdb.v1.ListDBReply
	4, // 6: api.kvdb.v1.Kvdb.SearchPrefix:output_type -> api.kvdb.v1.SearchPrefixReply
	6, // 7: api.kvdb.v1.Kvdb.Search:output_type -> api.kvdb.v1.SearchReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kvdb_v1_kvdb_proto_init() }
func file_kvdb_v1_kvdb_proto_init() {
	if File_kvdb_v1_kvdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kvdb_v1_kvdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvdbValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvdb_v1_kvdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvdb_v1_kvdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDBReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvdb_v1_kvdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPrefixRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvdb_v1_kvdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPrefixReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvdb_v1_kvdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvdb_v1_kvdb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kvdb_v1_kvdb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvdb_v1_kvdb_proto_goTypes,
		DependencyIndexes: file_kvdb_v1_kvdb_proto_depIdxs,
		MessageInfos:      file_kvdb_v1_kvdb_proto_msgTypes,
	}.Build()
	File_kvdb_v1_kvdb_proto = out.File
	file_kvdb_v1_kvdb_proto_rawDesc = nil
	file_kvdb_v1_kvdb_proto_goTypes = nil
	file_kvdb_v1_kvdb_proto_depIdxs = nil
}
